services:
  wireguard:
    image: lkarolewski/wg-manager:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - /etc/wireguard:/etc/wireguard
      - ./db:/app/prisma/db
    ports:
      - "8888:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL-file:./db/prod.db}
      - AUTH_SECRET=${AUTH_SECRET} # set to openssl rand -base64 32
      - AUTH_URL=${AUTH_URL} # update to external url http://localhost:3000/api/auth
      - GOOGLE_ID=${GOOGLE_ID}
      - GOOGLE_SECRET=${GOOGLE_SECRET}
