version: "3"
services:
  wireguard:
    # image: lkarolewski/wg-manager:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /etc/wireguard:/etc/wireguard
    ports:
      - "80:80"
      - "443:443"
    environment:
      - GOOGLE_ID=<insert>
      - GOOGLE_SECRET=<insert>
