name: build and publish

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Version
        id: version
        run: echo "version=$(date +'%y.%m.%d.')${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          # Add support for more platforms with QEMU (optional)
          # https://github.com/docker/setup-qemu-action
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Cache Docker layers
        uses: actions/cache@v4
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('**/package-lock.json', '**/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push Docker image
        run: |
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --cache-from "type=registry,ref=lkarolewski/wg-manager:latest" \
            --cache-to "type=local,dest=/tmp/.buildx-cache-new,mode=max" \
            --platform linux/amd64,linux/arm64 \
            --build-arg VERSION=${{ env.version }} \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --push \
            --tag lkarolewski/wg-manager:latest \
            --file ./Dockerfile ./

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Inspect image
        run: |
          docker buildx imagetools inspect lkarolewski/wg-manager:latest
