name: build and publish

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Version
        id: version
        run: echo "version=$(date +'%y.%m.%d.')${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          # Add support for more platforms with QEMU (optional)
          # https://github.com/docker/setup-qemu-action
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Docker Buildx (build)
        run: |
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --cache-to "type=local,dest=/tmp/.buildx-cache" \
            --platform linux/amd64,linux/arm64 \
            --build-arg VERSION=${{ env.version }}
            --output "type=image,push=false" \
            --tag lkarolewski/wg-manager:latest \
            --file ./Dockerfile ./

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Buildx (push)
        run: |
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --platform linux/amd64,linux/arm64 \
            --build-arg VERSION=${{ env.version }}
            --output "type=image,push=true" \
            --tag lkarolewski/wg-manager:latest \
            --file ./Dockerfile ./

      - name: Inspect image
        run: |
          docker buildx imagetools inspect lkarolewski/wg-manager:latest
